// <auto-generated />
namespace SurveyOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addnewmodel3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewmodel3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005081213591_add-new-model-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
