// <auto-generated />
namespace SurveyOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newmodelclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmodelclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202005040152557_new model class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
