// <auto-generated />
namespace SurveyOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Fix_model_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_model_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202004171012114_Fix_model_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
